### ISSUE TITLE
Ensure Sentry environments can be used

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#107]
Via Taiga Enschede SSC nr 9

The current version of Open Notificaties doesn't have Sentry environment support, this would be useful for combining multiple installs into a single Sentry project

This also seems to be necessary for ObjectTypes, can also be investigated

**Comment by Coperh** [comment]
As far as I know, this should already be implemented. It matches OpenZaak's settings which does allow this.

I think it was fixed in #149  indirectly
