### ISSUE TITLE
Abonnementen admin: show if the callback URL can be reached

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#108]
Taiga DH #524 

The 'abonnementen' admin listview can be improved by adding if the callback URLs can be reached (similar to how this is checked when creating the subscription via the API). This allows the admin to verify which subscriptions are still working as expected. The Taiga issue offers further suggestions.

**Comment by PeterVanBragt** [comment]
I can hereby confirm that this tickets can be picked up.

**Comment by stevenbal** [comment]
@alextreme I made a PR for this, but @annashamray correctly mentioned that this implementation (checking the status for every subscription on the page when opening the list view) will slow down the page quite significantly if there are a lot of them. Additionally, if there is more than 1 page (100+ subscriptions), admins will have to go through all pages to check the statuses

Maybe it would be better to implement an admin action which can be used to check the status for selected subscriptions (this would also allow them to select all subscriptions). What do you think of this?

**Comment by alextreme** [comment]
@stevenbal doing this via an admin action is fine, however note that admin actions aren't easily findable (even I forget that they are there). Adding a button in the listview per subscription to trigger this action should solve this problem

**Comment by stevenbal** [comment]
@alextreme I've changed it to a custom admin action with a shortcut button to trigger it for all Subscriptions. I've also added a filter on the result to make it easier to check which status checks failed

![HLgKUY3b67](https://github.com/user-attachments/assets/c0ffa11d-e904-4548-853b-97fef0b65694)

**Comment by alextreme** [comment]
@stevenbal looks good, thanks for improving this further
