### ISSUE TITLE
ON 1.5: lack of netcat causes celery to not start

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#120]
Raised by DH/JB:

In ON1.5 #114 / 1512-full-update netcat was removed from the Dockerfile. This causes the bin/wait_for_rabbitmq.sh script to not work, causing bin/celery_worker.sh to not be able to be executed. This in turn leads to notifications not being sent.

![image](https://github.com/open-zaak/open-notificaties/assets/226839/f81275a4-c522-4b38-9fb2-742d02c4c0a7)

https://github.com/open-zaak/open-notificaties/blob/main/bin/wait_for_rabbitmq.sh

Aside from the mistake, this indicates that docker/integrationtests are missing and (if confirmed) means that ON1.5 can't function as expected.

**Comment by annashamray** [comment]
I'll return `netcat` to the docker image, but creating a check for it is quite tricky, because celery container is created and it's running, it just waits infinitely for rabbitMq under the hood
Should we have a timeout for waiting? But which one?

**Comment by annashamray** [comment]
I've tried to add a limit of 1 min to the waiting time for rabbitMq, but it means that 1 min the container is running, so I don't know how to test it actually

**Comment by joeribekker** [comment]
@annashamray maybe just adjust the [wait_for_rabbitmq.sh](https://github.com/open-zaak/open-notificaties/blob/main/bin/wait_for_rabbitmq.sh) script to check if the command exists. If not, it exits and Celery container will not start at all.

```
if ! command -v nc &> /dev/null
then
    echo "netcat is not installed."
    exit 1
fi
```

**Comment by annashamray** [comment]
I've just tried and even if you throw an error in [wait_for_rabbitmq.sh](https://github.com/open-zaak/open-notificaties/blob/main/bin/wait_for_rabbitmq.sh) , `docker-compose up` command will sill be successful 

Maybe we need some integration tests in ON which would use different docker containers, like we have Postman tests in Open Zaak?

**Comment by alextreme** [comment]
Sounds good, fire up `docker-compose up` together with a client-testapp in Django for the callback URL, create an abonnement via the ON API, shoot in a notification and verify that the callback receives the notification

**Comment by annashamray** [comment]
I've created an issue from  Alex's comment
