### ISSUE TITLE
Open Notificaties view-config raises 500 error

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#141]
DH Taiga 555:

Going to https://notificaties.test.openzaak.nl/view-config/ raises a HTTP 500 error. 

https://sentry.maykinmedia.nl/organizations/maykin-media/issues/355206/?project=150&query=is%3Aunresolved

To be checked if this is still an issue (our test environment might be behind latest)

**Comment by Coperh** [comment]
From what it looks like, this was fixed a few months ago in #119. This has not been released yet.

It does not occur for me locally.

**Comment by alextreme** [comment]
Okay, then it's more a matter of ensuring that our OZ+ON test instances are updated after each release (@annashamray please ask @sjoerdie to do so)

**Comment by Coperh** [comment]
Further clarification: the change is not in 1.5.2 and needs to be released.
