### ISSUE TITLE
Help text buttons missaligned in admin

### ISSUE THREAD

**Issue by Coperh** [open-zaak/open-notificaties#150]
Similar issue to the one in the openzaak django4.2 update: open-zaak/open-zaak#1614 (Darkmode works as expected)

![Screenshot from 2024-04-30 17-38-09](https://github.com/open-zaak/open-notificaties/assets/3464144/9bf6b788-0f38-4274-b885-b282de384c00)

Fixed in:
- [x] Open Notificaties https://github.com/open-zaak/open-notificaties/pull/168
- [x] Open Klant https://github.com/maykinmedia/open-klant/pull/200
- [x] Objects API https://github.com/maykinmedia/objects-api/pull/421
- [x] Objecttypes API https://github.com/maykinmedia/objecttypes-api/pull/119
- [x] Open Zaak https://github.com/open-zaak/open-zaak/pull/1705
- [x] Referentielijsten API https://github.com/maykinmedia/referentielijsten/pull/18

**Comment by alextreme** [comment]
Also to check in OZ, Objects API...

**Comment by Coperh** [comment]
@annashamray Open-klant does seems to have issues in `admin/klantinteracties/internetaak/add/` see screenshot

![Screenshot from 2024-07-02 17-13-38](https://github.com/open-zaak/open-notificaties/assets/3464144/ab706a18-dc4d-4bdd-8f4d-148680fd7a1b)

Only this datetimefield and only in Open Klant seemingly

**Comment by Coperh** [comment]
Also the format issue I mentioned in https://github.com/maykinmedia/objecttypes-api/pull/119#pullrequestreview-2153675680 is also in open-zaak and referentielijsten

**Comment by annashamray** [comment]
@Coperh You are right, I've fixed it in OZ, I'll take a look at Referentielijsten now
