### ISSUE TITLE
Sta meerdere abonnementen toe met dezelfde callback URL

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#82]
Een concreet verzoek vanuit Den Haag is dat ze notificaties willen ontvangen voor een specifieke reeks zaaktypes op 1 en dezelfde callback URL.

E.e.a. zou handiger kunnen (bijvoorbeeld het filteren op catalogus ipv individuele zaaktypes, of het kunnen opgeven van een langere URL dan 200 tekens) echter waar ze op vastlopen is dat Open Notificaties het niet toestaat om meerdere abonnementen te hebben met dezelfde callback URL. Dit wordt afgedwongen door een unique=True, dus dit mag niet via de admin of via de API.

Unieke callback URLs is zo te zien geen vereiste van de standaard, dus mijn voorstel is om deze restrictie los te laten in de admin en in de API. Meerdere abonnementen op dezelfde callback URL zorgen dan voor meerdere notificaties, afhankelijk van hoe de filters voor een abonnement staan ingesteld.

**Comment by sergei-maertens** [comment]
Volgens mij was het de bedoeling dat je alle kanalen/abonnementen in de subscription opneemt onder de `kanalen` lijst. Anders zie ik niet goed waarom dat een lijst zou zijn van kanalen elk met apart mogelijke filters...

**Comment by alextreme** [comment]
@sergei-maertens heb je een voorbeeld van hoe je dan een subscription voor meerdere zaaktypes kan instellen?
