### ISSUE TITLE
Sentry error when a failed notification sends a too big response

### ISSUE THREAD

**Issue by Nath82** [open-zaak/open-notificaties#92]
#96

**Comment by annashamray** [comment]
Could you add a link to the Sentry issue?

**Comment by Nath82** [comment]
Yeah sorry I hadn't seen : https://sentry.maykinmedia.nl/organizations/maykin-media/issues/324573/events/43956493c6cd4649bad1233186a0bf93/?project=288&query=is%3Aunresolved
