### ISSUE TITLE
Add-Elastic-APM-support

### ISSUE THREAD

**Issue by Nath82** [open-zaak/open-notificaties#98]
#97 Adding elastic apm support to the project to monitor application performance.

**Comment by alextreme** [comment]
@Nath82 please expand your issue description to ensure it's clear (it should be more than a reference to your PR)

**Comment by alextreme** [comment]
@Nath82 I'd recommend to also make TRANSACTION_SAMPLE_RATE a setting that is configurable via an envvar. By default it can be 1.0, however with the number of transactions taking place for Open Notificaties it may make more sense to put it on 0.1 by default. This limits the amount of APM requests to only 1 in 10 transactions, which improves performance.

![image](https://github.com/open-zaak/open-notificaties/assets/226839/a776df92-0e60-4150-97d7-faee6a4444bb)
