### ISSUE TITLE
Add Notification uuid header to outgoing requests

### ISSUE THREAD

**Issue by alextreme** [open-zaak/open-notificaties#99]
From #95 

For correlation purposes, I'd consider adding an additional custom header to requests we send: X-Notification-ID: <uuid> so we can search for that in the request logs & correlate them with metadata from Sentry if something crashes (or with the logs from the remote system we are sending the notification to) and with the original notification that was sent to us (which should have an ID or we generate one, I think?).

**Comment by alextreme** [comment]
Discussed, and Steven's PR https://github.com/open-zaak/open-notificaties/pull/71 will need to be picked up, updated and merged in order to be able to do this

**Comment by annashamray** [comment]
This PR duplicates changes from #71 
What is the plan for #71 now?
